2024-11-20 10:23:14,652 - INFO - server listening on [::1]:8765
2024-11-20 10:23:14,653 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:23:14,653 - INFO - Server started on ws://localhost:8765
2024-11-20 10:23:22,252 - INFO - connection open
2024-11-20 10:23:22,252 - INFO - Player f6a2522d-29d8-4539-b628-bb12bdbb8032 connected.
2024-11-20 10:23:47,008 - INFO - connection open
2024-11-20 10:23:47,008 - INFO - Player 2388807b-1c53-4643-a310-df37e8bda64b connected.
2024-11-20 10:24:02,204 - INFO - Player 2388807b-1c53-4643-a310-df37e8bda64b moved to upper_engine.
2024-11-20 10:25:19,641 - INFO - Player 2388807b-1c53-4643-a310-df37e8bda64b moved to reactor.
2024-11-20 10:28:34,337 - INFO - Player 2388807b-1c53-4643-a310-df37e8bda64b disconnected.
2024-11-20 10:28:34,337 - INFO - connection closed
2024-11-20 10:28:34,337 - INFO - Player f6a2522d-29d8-4539-b628-bb12bdbb8032 disconnected.
2024-11-20 10:28:34,337 - INFO - connection closed
2024-11-20 10:29:37,143 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:29:37,143 - INFO - server listening on [::1]:8765
2024-11-20 10:29:37,143 - INFO - Server started on ws://localhost:8765
2024-11-20 10:29:42,439 - INFO - connection open
2024-11-20 10:29:42,439 - INFO - Player 0cf240ca-4f88-48ed-9e41-3197a04d46fe connected.
2024-11-20 10:29:43,545 - INFO - Player 0cf240ca-4f88-48ed-9e41-3197a04d46fe disconnected.
2024-11-20 10:29:43,545 - INFO - connection closed
2024-11-20 10:32:41,570 - INFO - connection open
2024-11-20 10:32:41,570 - INFO - Player 2e2293a9-44ba-4ac4-8e23-b5776448f0e5 connected.
2024-11-20 10:32:42,696 - INFO - Player 2e2293a9-44ba-4ac4-8e23-b5776448f0e5 disconnected.
2024-11-20 10:32:42,696 - INFO - connection closed
2024-11-20 10:33:21,506 - INFO - connection open
2024-11-20 10:33:21,506 - INFO - Player 4c2c8845-d6b6-4b9c-a2c5-f1fe062520d2 connected.
2024-11-20 10:33:23,573 - INFO - Player 4c2c8845-d6b6-4b9c-a2c5-f1fe062520d2 disconnected.
2024-11-20 10:33:23,573 - INFO - connection closed
2024-11-20 10:39:43,090 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:39:43,090 - INFO - server listening on [::1]:8765
2024-11-20 10:39:43,090 - INFO - Server started on ws://localhost:8765
2024-11-20 10:39:44,955 - INFO - connection open
2024-11-20 10:39:44,955 - INFO - Player 3261f0a4-ecd0-4c27-b20c-70a43a2034b2 connected.
2024-11-20 10:39:46,058 - INFO - Player 3261f0a4-ecd0-4c27-b20c-70a43a2034b2 disconnected.
2024-11-20 10:39:46,058 - INFO - connection closed
2024-11-20 10:39:52,568 - INFO - connection open
2024-11-20 10:39:52,568 - INFO - Player c382e9dd-a413-4d47-b141-c6c1c80eef87 connected.
2024-11-20 10:39:54,388 - INFO - Player c382e9dd-a413-4d47-b141-c6c1c80eef87 disconnected.
2024-11-20 10:39:54,388 - INFO - connection closed
2024-11-20 10:40:17,237 - INFO - connection open
2024-11-20 10:40:17,237 - INFO - Player 2756253a-b175-4224-9d24-627909cdd858 connected.
2024-11-20 10:40:17,976 - INFO - Player 2756253a-b175-4224-9d24-627909cdd858 disconnected.
2024-11-20 10:40:17,976 - INFO - connection closed
2024-11-20 10:40:38,989 - INFO - connection open
2024-11-20 10:40:38,989 - INFO - Player 5c4b0134-42c3-4dfc-86de-e5ff06dd6808 connected.
2024-11-20 10:40:40,486 - INFO - Player 5c4b0134-42c3-4dfc-86de-e5ff06dd6808 disconnected.
2024-11-20 10:40:40,486 - INFO - connection closed
2024-11-20 10:41:09,150 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:41:09,150 - INFO - server listening on [::1]:8765
2024-11-20 10:41:09,150 - INFO - Server started on ws://localhost:8765
2024-11-20 10:41:10,500 - INFO - connection open
2024-11-20 10:41:10,500 - INFO - Player 8becf9c3-37c5-41f8-8aa8-b00082754abd connected.
2024-11-20 10:41:14,329 - INFO - Player 8becf9c3-37c5-41f8-8aa8-b00082754abd disconnected.
2024-11-20 10:41:14,330 - INFO - connection closed
2024-11-20 10:41:33,519 - INFO - connection open
2024-11-20 10:41:33,519 - INFO - Player 81beab64-b458-41a0-80ed-20ff5b79ad69 connected.
2024-11-20 10:41:34,220 - INFO - Player 81beab64-b458-41a0-80ed-20ff5b79ad69 disconnected.
2024-11-20 10:41:34,220 - INFO - connection closed
2024-11-20 10:42:47,533 - INFO - server listening on [::1]:8765
2024-11-20 10:42:47,533 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:42:47,533 - INFO - Server started on ws://localhost:8765
2024-11-20 10:42:48,571 - INFO - connection open
2024-11-20 10:42:48,571 - INFO - Player 4e89ebb9-11d2-45d1-ba62-d961e20303e8 connected.
2024-11-20 10:42:50,595 - INFO - Player 4e89ebb9-11d2-45d1-ba62-d961e20303e8 disconnected.
2024-11-20 10:42:50,595 - INFO - connection closed
2024-11-20 10:43:43,095 - INFO - connection open
2024-11-20 10:43:43,095 - INFO - Player 00a3c8b5-71df-42ce-b81b-045b58d75765 connected.
2024-11-20 10:43:43,994 - INFO - Player 00a3c8b5-71df-42ce-b81b-045b58d75765 disconnected.
2024-11-20 10:43:43,994 - INFO - connection closed
2024-11-20 10:45:59,714 - INFO - connection open
2024-11-20 10:45:59,714 - INFO - Player 8aab4194-f4f2-4723-b1f6-88b31dda07a8 connected.
2024-11-20 10:46:00,776 - INFO - Player 8aab4194-f4f2-4723-b1f6-88b31dda07a8 disconnected.
2024-11-20 10:46:00,776 - INFO - connection closed
2024-11-20 10:46:48,581 - INFO - connection open
2024-11-20 10:46:48,581 - INFO - Player 2b0a0533-17df-4d58-8d5e-bdc33c1b52c0 connected.
2024-11-20 10:46:50,984 - INFO - Player 2b0a0533-17df-4d58-8d5e-bdc33c1b52c0 disconnected.
2024-11-20 10:46:50,984 - INFO - connection closed
2024-11-20 10:47:14,678 - INFO - connection open
2024-11-20 10:47:14,678 - INFO - Player 89e24e64-2c30-4b6d-a75c-da8331aa6169 connected.
2024-11-20 10:47:15,247 - INFO - Player 89e24e64-2c30-4b6d-a75c-da8331aa6169 disconnected.
2024-11-20 10:47:15,247 - INFO - connection closed
2024-11-20 10:57:05,524 - INFO - server listening on [::1]:8765
2024-11-20 10:57:05,524 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:57:05,524 - INFO - Server started on ws://localhost:8765
2024-11-20 10:57:07,903 - INFO - connection open
2024-11-20 10:57:07,903 - INFO - Player c7c5cc20-7fa3-44c3-b025-8f71099a5807 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 10:57:12,678 - INFO - Player c7c5cc20-7fa3-44c3-b025-8f71099a5807 moved to medbay. Room occupancy: {'cafeteria': 0, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 10:59:25,149 - INFO - Player c7c5cc20-7fa3-44c3-b025-8f71099a5807 disconnected.
2024-11-20 10:59:25,149 - INFO - connection closed
2024-11-20 10:59:29,834 - INFO - server listening on 127.0.0.1:8765
2024-11-20 10:59:29,835 - INFO - server listening on [::1]:8765
2024-11-20 10:59:29,835 - INFO - Server started on ws://localhost:8765
2024-11-20 10:59:31,082 - INFO - connection open
2024-11-20 10:59:31,082 - INFO - Player 5b16067a-5c4d-4eec-8d96-596794d0c65f connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 10:59:37,328 - INFO - Player 5b16067a-5c4d-4eec-8d96-596794d0c65f moved to upper_engine. Room occupancy: {'cafeteria': 0, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:00:07,565 - INFO - connection open
2024-11-20 11:00:07,566 - INFO - Player 67185747-a6ca-41e6-af8f-83618af336f5 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:00:16,980 - INFO - Player 67185747-a6ca-41e6-af8f-83618af336f5 moved to upper_engine. Room occupancy: {'cafeteria': 0, 'upper_engine': 2, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:00:21,861 - INFO - Player 67185747-a6ca-41e6-af8f-83618af336f5 moved to reactor. Room occupancy: {'cafeteria': 0, 'upper_engine': 1, 'reactor': 1, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:01:27,554 - INFO - Player 67185747-a6ca-41e6-af8f-83618af336f5 moved to security. Room occupancy: {'cafeteria': 0, 'upper_engine': 1, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:49:44,979 - INFO - Player 67185747-a6ca-41e6-af8f-83618af336f5 disconnected.
2024-11-20 11:49:44,979 - INFO - connection closed
2024-11-20 11:58:51,825 - INFO - Player 5b16067a-5c4d-4eec-8d96-596794d0c65f disconnected.
2024-11-20 11:58:51,826 - INFO - connection closed
2024-11-20 11:58:57,227 - INFO - server listening on 127.0.0.1:8765
2024-11-20 11:58:57,227 - INFO - server listening on [::1]:8765
2024-11-20 11:58:57,227 - INFO - Server started on ws://localhost:8765
2024-11-20 11:59:11,665 - INFO - connection open
2024-11-20 11:59:11,665 - INFO - Player fe19ba65-4502-4765-a637-13770cf32ecf connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:59:12,897 - INFO - Player fe19ba65-4502-4765-a637-13770cf32ecf disconnected.
2024-11-20 11:59:12,897 - INFO - connection closed
2024-11-20 11:59:33,950 - INFO - connection open
2024-11-20 11:59:33,951 - INFO - Player b76633c2-8477-45e0-b095-6acb2e2b604e connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:59:34,760 - INFO - Player b76633c2-8477-45e0-b095-6acb2e2b604e disconnected.
2024-11-20 11:59:34,761 - INFO - connection closed
2024-11-20 11:59:42,098 - INFO - connection open
2024-11-20 11:59:42,098 - INFO - Player 38f818cc-f4eb-4b8c-8d93-0e947842bd57 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:59:42,945 - INFO - Player 38f818cc-f4eb-4b8c-8d93-0e947842bd57 disconnected.
2024-11-20 11:59:42,945 - INFO - connection closed
2024-11-20 11:59:46,399 - INFO - connection open
2024-11-20 11:59:46,399 - INFO - Player e6404346-3aa4-4f1a-8279-51f9680b3482 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 11:59:47,218 - INFO - Player e6404346-3aa4-4f1a-8279-51f9680b3482 disconnected.
2024-11-20 11:59:47,218 - INFO - connection closed
2024-11-20 12:02:27,648 - INFO - connection open
2024-11-20 12:02:27,649 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd connected. Room occupancy: {'cafeteria': 5, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:02:40,956 - INFO - connection open
2024-11-20 12:02:40,957 - INFO - Player 9672e016-1560-4f30-8587-3c54645fc33f connected. Room occupancy: {'cafeteria': 6, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:02:50,930 - INFO - connection open
2024-11-20 12:02:50,930 - INFO - Player 9698f987-5664-4b74-9887-758f5995cb02 connected. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:02:56,252 - INFO - connection open
2024-11-20 12:02:56,252 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 connected. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:09,301 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:03:11,219 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:13,060 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:03:14,037 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:16,408 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to upper_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:17,658 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to reactor. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 1, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:20,342 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to upper_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:21,716 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:31,777 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:03:34,096 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:03:36,191 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:03:38,931 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:34,967 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:04:35,600 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:36,093 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:36,470 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to electrical. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:37,252 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to lower_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:37,657 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to electrical. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:38,193 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:38,675 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:39,191 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to upper_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:39,998 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:41,486 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to upper_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:04:59,771 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:05:00,618 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to engine_room. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:01,403 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to upper_engine. Room occupancy: {'cafeteria': 6, 'upper_engine': 2, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:02,129 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to reactor. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 1, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:02,607 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to security. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:03,444 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to electrical. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:04,117 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to lower_engine. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:04,440 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to electrical. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:04,791 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to security. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:05,233 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to engine_room. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:05,811 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to medbay. Room occupancy: {'cafeteria': 6, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:05:06,336 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 moved to cafeteria. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:42,997 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:05:44,172 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to upper_engine. Room occupancy: {'cafeteria': 7, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:12,836 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to cafeteria. Room occupancy: {'cafeteria': 8, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:13,544 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to medbay. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:06:14,817 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:15,779 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:16,402 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to electrical. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:19,598 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:20,507 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:06:21,281 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:00,387 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to engine_room. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:07,057 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd moved to security. Room occupancy: {'cafeteria': 7, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:12,289 - INFO - Player 9672e016-1560-4f30-8587-3c54645fc33f disconnected.
2024-11-20 12:07:12,289 - INFO - connection closed
2024-11-20 12:07:12,289 - INFO - Player 10da9c6a-1b50-47dc-95e8-2fcbed7bc727 disconnected.
2024-11-20 12:07:12,289 - INFO - connection closed
2024-11-20 12:07:12,290 - INFO - Player 3eca5cf2-263b-416f-ba57-c675144754fd disconnected.
2024-11-20 12:07:12,290 - INFO - connection closed
2024-11-20 12:07:12,290 - INFO - Player 9698f987-5664-4b74-9887-758f5995cb02 disconnected.
2024-11-20 12:07:12,290 - INFO - connection closed
2024-11-20 12:07:15,423 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:07:15,423 - INFO - server listening on [::1]:8765
2024-11-20 12:07:15,423 - INFO - Server started on ws://localhost:8765
2024-11-20 12:07:17,008 - INFO - connection open
2024-11-20 12:07:17,009 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:17,953 - INFO - connection open
2024-11-20 12:07:17,953 - INFO - Player 70233605-cbdd-4e42-94a7-c36f6bbf4dd2 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:21,093 - INFO - connection open
2024-11-20 12:07:21,094 - INFO - Player 1836c93d-3138-4b67-ae4a-300ac2d84c39 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:07:22,216 - INFO - connection open
2024-11-20 12:07:22,216 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:48,471 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:08:49,341 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:54,686 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:55,515 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:56,087 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:56,523 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:56,890 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:57,314 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:08:58,039 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:08:58,454 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:10:43,033 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:10:43,546 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:10:44,313 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to upper_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:10:44,651 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:10:45,390 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to upper_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:10:45,980 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:12:53,702 - INFO - Player 6a1a239e-72bb-401c-9208-12048aeacf9a disconnected.
2024-11-20 12:12:53,703 - INFO - connection closed
2024-11-20 12:12:53,703 - INFO - Player 1836c93d-3138-4b67-ae4a-300ac2d84c39 disconnected.
2024-11-20 12:12:53,703 - INFO - connection closed
2024-11-20 12:12:53,703 - INFO - Player 70233605-cbdd-4e42-94a7-c36f6bbf4dd2 disconnected.
2024-11-20 12:12:53,703 - INFO - connection closed
2024-11-20 12:12:53,703 - INFO - Player 7871e67a-c72c-4ee7-b04a-8ca64655353e disconnected.
2024-11-20 12:12:53,703 - INFO - connection closed
2024-11-20 12:13:43,074 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:13:43,074 - INFO - server listening on [::1]:8765
2024-11-20 12:13:43,074 - INFO - Server started on ws://localhost:8765
2024-11-20 12:13:51,456 - INFO - connection open
2024-11-20 12:13:51,457 - INFO - Player 0e94b836-8d4a-4ddc-b73f-a4b74298448b connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:13:52,478 - INFO - connection open
2024-11-20 12:13:52,479 - INFO - Player 1dc93b2d-5e4c-4fb5-aa04-beabf6a1c3d8 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:13:55,447 - INFO - connection open
2024-11-20 12:13:55,447 - INFO - Player 08a48531-ad3f-4bcf-b671-9da303299439 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:13:56,632 - INFO - connection open
2024-11-20 12:13:56,632 - INFO - Player 5be0642a-6904-408b-999b-331430e3860b connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:14:55,772 - INFO - Player 08a48531-ad3f-4bcf-b671-9da303299439 disconnected.
2024-11-20 12:14:55,772 - INFO - connection closed
2024-11-20 12:14:55,772 - INFO - Player 1dc93b2d-5e4c-4fb5-aa04-beabf6a1c3d8 disconnected.
2024-11-20 12:14:55,772 - INFO - connection closed
2024-11-20 12:14:55,772 - INFO - Player 0e94b836-8d4a-4ddc-b73f-a4b74298448b disconnected.
2024-11-20 12:14:55,772 - INFO - connection closed
2024-11-20 12:14:55,772 - INFO - Player 5be0642a-6904-408b-999b-331430e3860b disconnected.
2024-11-20 12:14:55,772 - INFO - connection closed
2024-11-20 12:16:26,545 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:16:26,545 - INFO - server listening on [::1]:8765
2024-11-20 12:16:26,545 - INFO - Server started on ws://localhost:8765
2024-11-20 12:16:29,054 - INFO - connection open
2024-11-20 12:16:29,054 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:30,275 - INFO - connection open
2024-11-20 12:16:30,275 - INFO - Player 7dc131ba-9989-4e43-a9f2-1065fbaf24d2 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:32,661 - INFO - connection open
2024-11-20 12:16:32,661 - INFO - Player 8b991cdc-727a-44ff-ac6e-0dc60c971d6c connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:33,947 - INFO - connection open
2024-11-20 12:16:33,947 - INFO - Player 2b3f6503-7083-4907-8358-6d85be8dd315 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:40,478 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:16:41,676 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:42,582 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:16:43,547 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:16:44,465 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:17:00,675 - INFO - Player 8b991cdc-727a-44ff-ac6e-0dc60c971d6c moved to medbay. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 2}
2024-11-20 12:17:01,108 - INFO - Player 8b991cdc-727a-44ff-ac6e-0dc60c971d6c moved to cafeteria. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:17:25,434 - INFO - Player f3085063-6e17-4a4b-a20d-567df735307f disconnected.
2024-11-20 12:17:25,434 - INFO - connection closed
2024-11-20 12:17:25,434 - INFO - Player 2b3f6503-7083-4907-8358-6d85be8dd315 disconnected.
2024-11-20 12:17:25,434 - INFO - connection closed
2024-11-20 12:17:25,435 - INFO - Player 8b991cdc-727a-44ff-ac6e-0dc60c971d6c disconnected.
2024-11-20 12:17:25,435 - INFO - connection closed
2024-11-20 12:17:25,435 - INFO - Player 7dc131ba-9989-4e43-a9f2-1065fbaf24d2 disconnected.
2024-11-20 12:17:25,435 - INFO - connection closed
2024-11-20 12:17:34,272 - INFO - server listening on [::1]:8765
2024-11-20 12:17:34,272 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:17:34,278 - INFO - Server started on ws://localhost:8765
2024-11-20 12:17:35,904 - INFO - connection open
2024-11-20 12:17:35,904 - INFO - Player b04ebf54-ea77-4e0e-981a-54de33323df8 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:17:41,015 - INFO - connection open
2024-11-20 12:17:41,016 - INFO - Player 201fae7d-bf54-408a-bc94-b8f271fc3069 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:17:43,793 - INFO - connection open
2024-11-20 12:17:43,794 - INFO - Player da35816c-f59e-4b56-b0dd-c5b0026c3238 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:17:44,869 - INFO - connection open
2024-11-20 12:17:44,869 - INFO - Player d7651c10-1639-46ff-bac1-17c3eb8d627a connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:18:43,306 - INFO - Player 201fae7d-bf54-408a-bc94-b8f271fc3069 disconnected.
2024-11-20 12:18:43,307 - INFO - connection closed
2024-11-20 12:18:43,308 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 99, in handle_connection
    del self.player_status[player_id]
  File "/Users/ohadr/text_among_us/game.py", line 220, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:18:43,312 - INFO - connection closed
2024-11-20 12:18:43,312 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 99, in handle_connection
    del self.player_status[player_id]
  File "/Users/ohadr/text_among_us/game.py", line 220, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:18:43,313 - INFO - connection closed
2024-11-20 12:18:43,313 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 99, in handle_connection
    del self.player_status[player_id]
  File "/Users/ohadr/text_among_us/game.py", line 220, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:18:43,313 - INFO - connection closed
2024-11-20 12:18:45,956 - INFO - server listening on [::1]:8765
2024-11-20 12:18:45,956 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:18:45,956 - INFO - Server started on ws://localhost:8765
2024-11-20 12:18:46,968 - INFO - connection open
2024-11-20 12:18:46,969 - INFO - Player 565400dd-dffc-4a13-ad89-9ddd0d9b20e5 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:18:53,930 - INFO - connection open
2024-11-20 12:18:53,932 - INFO - Player 10af1efd-016d-4c78-b2df-93068ccd4801 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:18:57,495 - INFO - Player 10af1efd-016d-4c78-b2df-93068ccd4801 moved to medbay. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:00,974 - INFO - connection open
2024-11-20 12:19:00,975 - INFO - Player 7781de01-63e3-4320-abd3-0183821f7052 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:05,837 - INFO - connection open
2024-11-20 12:19:05,839 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:10,569 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 2}
2024-11-20 12:19:11,148 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to cafeteria. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:11,914 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to upper_engine. Room occupancy: {'cafeteria': 2, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:12,718 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:13,896 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to upper_engine. Room occupancy: {'cafeteria': 2, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:14,626 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:15,334 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 2}
2024-11-20 12:19:15,802 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to cafeteria. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:19:18,665 - INFO - Player 10af1efd-016d-4c78-b2df-93068ccd4801 moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:20,508 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:20:21,356 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:21,691 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:22,355 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:22,737 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:23,381 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:20:25,461 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:26,274 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:20:26,854 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:28,492 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to upper_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:31,550 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:32,457 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:20:33,158 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:33,765 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:34,791 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:35,413 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:36,242 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to reactor. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 1, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:48,324 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to upper_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:49,475 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:50,076 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to upper_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 1, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:20:50,381 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:27,842 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:21:28,355 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:29,035 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:35,733 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:36,443 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:36,843 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:37,164 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:21:37,714 - INFO - Player 4c7122c1-0bfd-40ba-a57a-f1bc7a4d5dee moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:23:24,961 - INFO - Player 10af1efd-016d-4c78-b2df-93068ccd4801 disconnected.
2024-11-20 12:23:24,962 - INFO - connection closed
2024-11-20 12:23:24,963 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:23:24,964 - INFO - connection closed
2024-11-20 12:23:24,965 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:23:24,965 - INFO - connection closed
2024-11-20 12:23:24,965 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:23:24,966 - INFO - connection closed
2024-11-20 12:23:41,150 - INFO - server listening on [::1]:8765
2024-11-20 12:23:41,150 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:23:41,150 - INFO - Server started on ws://localhost:8765
2024-11-20 12:24:42,932 - INFO - connection open
2024-11-20 12:24:42,933 - INFO - Player 67b5495d-ddad-4e08-9de9-59fc2a5d6c15 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:24:50,032 - INFO - connection open
2024-11-20 12:24:50,033 - INFO - Player e3437de2-f908-4c60-b814-2ffa85aa87fb connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:24:59,031 - INFO - connection open
2024-11-20 12:24:59,032 - INFO - Player 80424226-06f9-44ff-a532-2a3ec694656e connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:25:03,244 - INFO - connection open
2024-11-20 12:25:03,246 - INFO - Player 57626581-40a2-4274-a791-57b94e3e2991 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:25:23,234 - INFO - Player e3437de2-f908-4c60-b814-2ffa85aa87fb disconnected.
2024-11-20 12:25:23,234 - INFO - connection closed
2024-11-20 12:25:23,235 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:25:23,236 - INFO - connection closed
2024-11-20 12:25:23,687 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:25:23,687 - INFO - connection closed
2024-11-20 12:25:23,688 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 223, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:25:23,688 - INFO - connection closed
2024-11-20 12:33:36,157 - INFO - server listening on [::1]:8765
2024-11-20 12:33:36,157 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:33:36,158 - INFO - Server started on ws://localhost:8765
2024-11-20 12:33:38,521 - INFO - connection open
2024-11-20 12:33:38,523 - INFO - Player 6909140f-c409-4967-bb70-601f4900c753 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:33:45,130 - INFO - connection open
2024-11-20 12:33:45,130 - INFO - Player 05671507-b88f-43dc-a4de-cee692163cff connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:33:48,640 - INFO - connection open
2024-11-20 12:33:48,641 - INFO - Player b9c511c9-d279-46cc-98cd-edd71ae8a6ab connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:33:49,643 - INFO - connection open
2024-11-20 12:33:49,644 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:34:05,997 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:34:07,650 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:34:08,423 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:34:15,186 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:34:16,112 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:34:27,184 - INFO - Player b9c511c9-d279-46cc-98cd-edd71ae8a6ab moved to medbay. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 1}
2024-11-20 12:34:36,858 - INFO - Player 6b4ece77-3ef8-40bc-aeb7-7ac2e33bdf8b disconnected.
2024-11-20 12:34:36,859 - INFO - connection closed
2024-11-20 12:34:36,860 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:34:36,867 - INFO - connection closed
2024-11-20 12:34:36,867 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:34:36,868 - INFO - connection closed
2024-11-20 12:34:36,868 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:34:36,868 - INFO - connection closed
2024-11-20 12:36:00,944 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:36:00,944 - INFO - server listening on [::1]:8765
2024-11-20 12:36:00,944 - INFO - Server started on ws://localhost:8765
2024-11-20 12:36:01,928 - INFO - connection open
2024-11-20 12:36:01,929 - INFO - Player c57efc00-27d9-4f24-858d-067ed40721ee connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:36:01,968 - INFO - connection open
2024-11-20 12:36:01,968 - INFO - Player c90e90e6-8bec-4f1b-9242-f093469b7c46 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:36:01,987 - INFO - connection open
2024-11-20 12:36:01,987 - INFO - Player 10b7a5ae-d5a0-40d2-a887-e10cbdaf03fa connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:36:01,992 - INFO - connection open
2024-11-20 12:36:01,993 - INFO - Player 076ff216-ace2-46e0-b1fd-65c30417ece2 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:36:33,561 - INFO - Player 076ff216-ace2-46e0-b1fd-65c30417ece2 disconnected.
2024-11-20 12:36:33,562 - INFO - connection closed
2024-11-20 12:36:33,563 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:36:33,567 - INFO - connection closed
2024-11-20 12:36:33,567 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:36:33,568 - INFO - connection closed
2024-11-20 12:36:33,568 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    await self.broadcast_message({
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:36:33,568 - INFO - connection closed
2024-11-20 12:37:15,474 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:37:15,474 - INFO - server listening on [::1]:8765
2024-11-20 12:37:15,474 - INFO - Server started on ws://localhost:8765
2024-11-20 12:37:20,148 - INFO - connection open
2024-11-20 12:37:20,149 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:37:20,159 - INFO - connection open
2024-11-20 12:37:20,159 - INFO - Player 7d91a547-c5f4-4e1a-8429-e581c334f0eb connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:37:20,262 - INFO - connection open
2024-11-20 12:37:20,263 - INFO - Player 174b26b4-0b64-4654-a9e7-4662d06f6cf9 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:37:20,270 - INFO - connection open
2024-11-20 12:37:20,270 - INFO - Player 4d7960aa-329c-4f3a-96c3-85794847f1ac connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:37:22,185 - INFO - Player 7d91a547-c5f4-4e1a-8429-e581c334f0eb moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:37:40,405 - INFO - Player 7d91a547-c5f4-4e1a-8429-e581c334f0eb moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:37:42,390 - INFO - Player 7d91a547-c5f4-4e1a-8429-e581c334f0eb moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:37:53,312 - INFO - Player 174b26b4-0b64-4654-a9e7-4662d06f6cf9 moved to storage. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 0}
2024-11-20 12:37:57,950 - INFO - Player 174b26b4-0b64-4654-a9e7-4662d06f6cf9 moved to cafeteria. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:37:58,949 - INFO - Player 174b26b4-0b64-4654-a9e7-4662d06f6cf9 moved to storage. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 0}
2024-11-20 12:38:07,673 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to medbay. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 1}
2024-11-20 12:38:09,212 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to cafeteria. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 0}
2024-11-20 12:38:10,983 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to medbay. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 1}
2024-11-20 12:38:11,877 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to cafeteria. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 0}
2024-11-20 12:38:12,598 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to medbay. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 1}
2024-11-20 12:38:15,534 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to cafeteria. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 0}
2024-11-20 12:38:16,289 - INFO - Player e10adcc1-1b19-442a-aa42-b40759b9565e moved to medbay. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 2, 'medbay': 1}
2024-11-20 12:40:19,366 - INFO - Player 4d7960aa-329c-4f3a-96c3-85794847f1ac disconnected.
2024-11-20 12:40:19,366 - INFO - connection closed
2024-11-20 12:40:19,367 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    "type": "player_update",
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:40:19,371 - INFO - connection closed
2024-11-20 12:40:19,371 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    "type": "player_update",
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:40:19,372 - INFO - connection closed
2024-11-20 12:40:19,372 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 103, in handle_connection
    "type": "player_update",
  File "/Users/ohadr/text_among_us/game.py", line 224, in broadcast_message
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:40:19,372 - INFO - connection closed
2024-11-20 12:43:34,330 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:43:34,330 - INFO - server listening on [::1]:8765
2024-11-20 12:43:34,330 - INFO - Server started on ws://localhost:8765
2024-11-20 12:43:37,014 - INFO - connection open
2024-11-20 12:43:37,014 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:37,014 - INFO - connection open
2024-11-20 12:43:37,014 - INFO - Player 75f54973-ce06-40e8-8550-1e302d57e479 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:37,033 - INFO - connection open
2024-11-20 12:43:37,034 - INFO - Player 8ddc7df5-b317-4656-8c94-2d9dd95f5e6f connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:37,036 - INFO - connection open
2024-11-20 12:43:37,037 - INFO - Player 8fa1e3d3-9449-4e8d-81e0-037084c89646 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:45,792 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:43:46,420 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:46,971 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:47,427 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:47,911 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:48,339 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:43:48,701 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:49,063 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:49,411 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:50,100 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to reactor. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 1, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:50,708 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to security. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 1, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:51,660 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to electrical. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 1, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:52,280 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:53,516 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to storage. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 1, 'medbay': 0}
2024-11-20 12:43:54,346 - INFO - Player 0d207605-c40a-44f4-a0cd-f98422ec89d9 moved to cafeteria. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:43:59,555 - INFO - Player 8ddc7df5-b317-4656-8c94-2d9dd95f5e6f moved to medbay. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 1}
2024-11-20 12:43:59,940 - INFO - Player 8ddc7df5-b317-4656-8c94-2d9dd95f5e6f moved to engine_room. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 1, 'storage': 0, 'medbay': 0}
2024-11-20 12:44:00,305 - INFO - Player 8ddc7df5-b317-4656-8c94-2d9dd95f5e6f moved to lower_engine. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 1, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:47:07,091 - INFO - Player 8fa1e3d3-9449-4e8d-81e0-037084c89646 disconnected.
2024-11-20 12:47:07,092 - INFO - connection closed
2024-11-20 12:47:07,093 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:47:07,097 - INFO - connection closed
2024-11-20 12:47:07,097 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:47:07,098 - INFO - connection closed
2024-11-20 12:47:07,098 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:47:07,098 - INFO - connection closed
2024-11-20 12:47:09,370 - INFO - server listening on [::1]:8765
2024-11-20 12:47:09,370 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:47:09,370 - INFO - Server started on ws://localhost:8765
2024-11-20 12:47:11,409 - INFO - connection open
2024-11-20 12:47:11,410 - INFO - Player f0a352b9-6a43-4ff7-a7cf-5621a3d2a18b connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:47:11,411 - INFO - connection open
2024-11-20 12:47:11,411 - INFO - Player 0d9f387d-43b1-4d2a-8f2e-bd5192f3f1d0 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:47:11,417 - INFO - connection open
2024-11-20 12:47:11,417 - INFO - Player 09911b2f-e28d-494d-9d7b-68cabe34dc6d connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:47:11,442 - INFO - connection open
2024-11-20 12:47:11,442 - INFO - Player 93340d44-4e8d-4e47-9898-66b6fd4747ec connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:49:46,395 - INFO - Player 93340d44-4e8d-4e47-9898-66b6fd4747ec disconnected.
2024-11-20 12:49:46,395 - INFO - connection closed
2024-11-20 12:49:46,396 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:49:46,401 - INFO - connection closed
2024-11-20 12:49:46,401 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:49:46,401 - INFO - connection closed
2024-11-20 12:49:46,401 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:49:46,401 - INFO - connection closed
2024-11-20 12:50:01,176 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:50:01,177 - INFO - server listening on [::1]:8765
2024-11-20 12:50:01,177 - INFO - Server started on ws://localhost:8765
2024-11-20 12:50:04,544 - INFO - connection open
2024-11-20 12:50:04,545 - INFO - Player 99a54d2d-a9ab-4eb5-8ba8-187c964a6eab connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:50:04,582 - INFO - connection open
2024-11-20 12:50:04,583 - INFO - Player 0f479d77-f4ad-4cb4-92e6-321aaafb3823 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:50:04,584 - INFO - connection open
2024-11-20 12:50:04,584 - INFO - Player 71a19632-3456-4db0-b390-37442176c795 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:50:04,585 - INFO - connection open
2024-11-20 12:50:04,585 - INFO - Player e6508d21-6afe-4252-b6b5-cd3554552bcb connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:50:56,317 - INFO - Player 71a19632-3456-4db0-b390-37442176c795 disconnected.
2024-11-20 12:50:56,318 - INFO - connection closed
2024-11-20 12:50:56,318 - INFO - Player 99a54d2d-a9ab-4eb5-8ba8-187c964a6eab disconnected.
2024-11-20 12:50:56,318 - INFO - connection closed
2024-11-20 12:50:56,352 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:50:56,358 - INFO - connection closed
2024-11-20 12:50:56,358 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:50:56,359 - INFO - connection closed
2024-11-20 12:50:59,080 - INFO - server listening on [::1]:8765
2024-11-20 12:50:59,080 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:50:59,080 - INFO - Server started on ws://localhost:8765
2024-11-20 12:51:01,438 - INFO - connection open
2024-11-20 12:51:01,438 - INFO - Player d4a720d2-5892-4d56-8d5f-280516fd0bcd connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:01,440 - INFO - connection open
2024-11-20 12:51:01,440 - INFO - Player 14409fbf-02ec-4301-b951-d3e902a75b65 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:01,479 - INFO - connection open
2024-11-20 12:51:01,479 - INFO - Player 2504b6e9-5a96-468d-af65-467346c13c3f connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:01,480 - INFO - connection open
2024-11-20 12:51:01,480 - INFO - Player 436dcedb-41fe-4220-93b2-101a080a5280 connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:13,021 - INFO - Player 436dcedb-41fe-4220-93b2-101a080a5280 disconnected.
2024-11-20 12:51:13,021 - INFO - connection closed
2024-11-20 12:51:13,022 - INFO - Player d4a720d2-5892-4d56-8d5f-280516fd0bcd disconnected.
2024-11-20 12:51:13,022 - INFO - connection closed
2024-11-20 12:51:13,023 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:51:13,025 - INFO - connection closed
2024-11-20 12:51:13,025 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:51:13,026 - INFO - connection closed
2024-11-20 12:51:14,652 - INFO - server listening on 127.0.0.1:8765
2024-11-20 12:51:14,652 - INFO - server listening on [::1]:8765
2024-11-20 12:51:14,652 - INFO - Server started on ws://localhost:8765
2024-11-20 12:51:17,776 - INFO - connection open
2024-11-20 12:51:17,777 - INFO - Player 4733306c-eccf-4496-8a6b-47d3df3a477b connected. Room occupancy: {'cafeteria': 1, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:17,819 - INFO - connection open
2024-11-20 12:51:17,819 - INFO - Player f771cc2f-df00-473c-bef1-cc6dce5eb9f1 connected. Room occupancy: {'cafeteria': 2, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:17,841 - INFO - connection open
2024-11-20 12:51:17,842 - INFO - Player f38ace70-be31-4ebb-adba-764b5131f363 connected. Room occupancy: {'cafeteria': 3, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:51:17,860 - INFO - connection open
2024-11-20 12:51:17,860 - INFO - Player fc0a6b38-c0e2-483a-bee4-060965c3d4ce connected. Room occupancy: {'cafeteria': 4, 'upper_engine': 0, 'reactor': 0, 'security': 0, 'electrical': 0, 'lower_engine': 0, 'engine_room': 0, 'storage': 0, 'medbay': 0}
2024-11-20 12:52:42,376 - INFO - Player fc0a6b38-c0e2-483a-bee4-060965c3d4ce disconnected.
2024-11-20 12:52:42,377 - INFO - connection closed
2024-11-20 12:52:42,378 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:52:42,381 - INFO - connection closed
2024-11-20 12:52:42,381 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:52:42,381 - INFO - connection closed
2024-11-20 12:52:42,381 - ERROR - connection handler failed
Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
  File "/Users/ohadr/text_among_us/game.py", line 102, in handle_connection
    await self.broadcast_message(
  File "/Users/ohadr/text_among_us/game.py", line 243, in broadcast_message
    await player["websocket"].send(json.dumps(message))
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/ohadr/.pyenv/versions/3.10.10/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 934, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
2024-11-20 12:52:42,382 - INFO - connection closed
